from __future__ import annotations
import numpy
import numpy.typing
import typing
__all__: list[str] = ['KdTree', 'KnnGraph']
class KdTree:
    def __init__(self, points: numpy.ndarray) -> None:
        ...
    def query_knn(self, query: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], k: typing.SupportsInt | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.int32]:
        ...
    def query_knn_index(self, index: typing.SupportsInt | typing.SupportsIndex, k: typing.SupportsInt | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.int32]:
        ...
    def query_radius(self, query: typing.Annotated[numpy.typing.ArrayLike, numpy.float32], radius: typing.SupportsFloat | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.int32]:
        ...
    def query_radius_index(self, index: typing.SupportsInt | typing.SupportsIndex, radius: typing.SupportsFloat | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.int32]:
        ...
    @property
    def size(self) -> int:
        ...
class KnnGraph:
    def __init__(self, points: numpy.ndarray, graph_k: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def query_knn_index(self, index: typing.SupportsInt | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.int32]:
        ...
    def query_radius_index(self, index: typing.SupportsInt | typing.SupportsIndex, radius: typing.SupportsFloat | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.int32]:
        ...
    @property
    def size(self) -> int:
        ...
